// booths.js — booths.json をそのまま埋め込んだもの（file:// でも動くように fetch を使いません）
// 事実の正は booths.json です。内容を変えるときは booths.json を直してから、このファイルを作り直してください。
window.FESTA_DATA = {
 "event": {
  "name": "北中城村ウェルネススポーツフェスタ2026",
  "date": "2026-12-13",
  "dateLabel": "2026年12月13日（日）",
  "time": "10:00〜15:00",
  "venue": "北中城村中央公民館 ホール",
  "address": "沖縄県中頭郡北中城村字仲順435",
  "parking": "無料駐車場139台",
  "organizer": "主催 北中城村観光協会／企画運営 ゆいどころ整体",
  "fee": "入場・体験 無料",
  "contact": "ゆいどころ（比嘉）080-6484-5121"
 },
 "booths": [
  {
   "id": "haihai",
   "name": "ハイハイレース",
   "short": "はいはい",
   "zone": "B 動くゾーン（舞台）",
   "time": "10:50〜11:20",
   "duration": "1レース5分・3レース",
   "target": "ハイハイができる赤ちゃんと保護者（月齢の制限なし）",
   "capacity": 12,
   "capacityNote": "9/12 なつきさん指示：午前の部12人",
   "reserve": true,
   "unit": "組",
   "desc": "赤ちゃんの「はじめて」をみんなで応援するレース。動物の整理券を首にかけて、名前を呼ばれたらスタート。ゴールしたら金メダル。",
   "exhibitor": "hapisma",
   "status": "確定",
   "meet": "開始10分前に舞台の前へ集合してください。時間までに来られない場合は、当日枠の方にお譲りします",
   "start": "10:50",
   "end": "11:20"
  },
  {
   "id": "yochiyochi",
   "name": "よちよちレース",
   "short": "よちよち",
   "zone": "B 動くゾーン（舞台）",
   "time": "13:35〜14:05",
   "duration": "1レース5分・3レース",
   "target": "よちよち歩くお子さんと保護者。月齢の制限なし",
   "capacity": 12,
   "capacityNote": "9/12 なつきさん指示：午後の部12人",
   "reserve": true,
   "unit": "組",
   "desc": "歩きはじめの子どもたちのレース。転ばないようにスタッフとボランティアが見守ります。",
   "exhibitor": "hapisma",
   "status": "確定",
   "meet": "開始10分前に舞台の前へ集合してください。時間までに来られない場合は、当日枠の方にお譲りします",
   "start": "13:35",
   "end": "14:05"
  },
  {
   "id": "kids",
   "name": "れなさんの運動あそび（午前の部・午後の部）",
   "short": "運動あそび",
   "zone": "B 動くゾーン",
   "time": "午前の部／午後の部（時間は調整中）",
   "duration": "30分（案）",
   "target": "午前＝子ども・親子（アニマルフロー）／午後＝小学校高学年・中学生（大縄跳び対決・綱引き・ロープ）",
   "capacity": 30,
   "reserve": true,
   "unit": "名",
   "desc": "午前は動物の動きをまねして楽しく体を動かす親子向け。午後は小学校高学年・中学生向けに、大縄跳び対決・大綱引き・ロープのエクササイズ（内容は調整中）。",
   "exhibitor": "rena",
   "status": "仮",
   "capacityNote": "9/12 なつきさん指示：午前15人・午後15人",
   "slots": [
    "kids_am",
    "kids_pm"
   ],
   "meet": "開始5分前にブースへお越しください。来られない場合は、当日枠の方にお譲りします"
  },
  {
   "id": "chair",
   "name": "チェアエクササイズ（高齢者向け）",
   "short": "チェア体操",
   "zone": "B 動くゾーン",
   "time": "時間は調整中",
   "duration": "20分（案）",
   "target": "高齢の方・イスに座ったまま動きたい方",
   "capacity": 0,
   "reserve": false,
   "unit": "",
   "desc": "イスに座ったままできる体操。担当はれなさん か もとぶ糀のもときさん（調整中）。予約なしで参加できます。",
   "exhibitor": "",
   "status": "仮"
  },
  {
   "id": "adult",
   "name": "大人エクササイズ（クバトレ）",
   "short": "大人エクササイズ",
   "zone": "B 動くゾーン",
   "time": "前半・後半 各1コマ（30分・案）",
   "duration": "30分",
   "target": "大人",
   "capacity": 15,
   "reserve": true,
   "unit": "名",
   "desc": "頑張らないトレーニングを体験。人数はこれから決めます（予約制）。",
   "exhibitor": "kubatore",
   "status": "仮",
   "capacityNote": "要確認（人数はこれから決める・仮に15）",
   "meet": "開始5分前にお越しください。来られない場合は、当日枠の方にお譲りします"
  },
  {
   "id": "ashimomi",
   "name": "足もみ体験",
   "short": "足もみ",
   "zone": "C-1 ケアブース",
   "time": "10時・11時・12時・13時・14時（各10分）",
   "duration": "10分",
   "target": "大人（体験したい小中学生・未就学児もOK）",
   "capacity": 5,
   "capacityNote": "9/12 なつきさん指示：5枠×1人",
   "reserve": true,
   "unit": "名",
   "desc": "「寝ても疲れがとれない」「なんとなく不調が続く」そんなことありませんか？足は全身を支える土台。台湾式の本格足もみで、足が軽くなり、全身が温まる感覚を体験してみませんか？",
   "exhibitor": "kazetotaiyo",
   "status": "確定",
   "caution": "妊娠初期（妊娠中で不安な方）、生理中、重度の心疾患のある方は受けられないことがあります",
   "slots": [
    "ashimomi_10",
    "ashimomi_11",
    "ashimomi_12",
    "ashimomi_13",
    "ashimomi_14"
   ],
   "meet": "開始5分前にブースへお越しください。来られない場合は、当日枠の方にお譲りします"
  },
  {
   "id": "seitai_yuimaru",
   "name": "整体体験（ゆいまーる）",
   "short": "整体",
   "zone": "C-2 ケアブース",
   "time": "10:00〜15:00の中で15分（案）",
   "duration": "15分（案）",
   "target": "大人",
   "capacity": 6,
   "capacityNote": "要確認（企画書待ち・仮の数）",
   "reserve": true,
   "unit": "名",
   "desc": "北中城村のよもぎ蒸しと水整体のサロン「ゆいまーる」の整体を15分体験。",
   "exhibitor": "yuimaru",
   "status": "仮",
   "meet": "開始5分前にブースへお越しください。来られない場合は、当日枠の方にお譲りします"
  },
  {
   "id": "conditioning",
   "name": "コンディショニング体験（クバトレ）",
   "short": "コンディショニング",
   "zone": "C-3 ケアブース",
   "time": "10:00〜15:00の中で15分（案）",
   "duration": "15分（案）",
   "target": "大人・スポーツをする子ども",
   "capacity": 6,
   "capacityNote": "要確認（企画書待ち・仮の数）",
   "reserve": true,
   "unit": "名",
   "desc": "理学療法士による体のチェックとコンディショニング。頑張らないトレーニングの入口です。",
   "exhibitor": "kubatore",
   "status": "仮",
   "meet": "開始5分前にブースへお越しください。来られない場合は、当日枠の方にお譲りします"
  },
  {
   "id": "seitai_motobu",
   "name": "整体体験（もとぶ糀工房）",
   "short": "整体",
   "zone": "C-4 ケアブース",
   "time": "10:00〜15:00の中で15分（案）",
   "duration": "15分（案）",
   "target": "大人",
   "capacity": 6,
   "capacityNote": "要確認（企画書待ち・仮の数）",
   "reserve": true,
   "unit": "名",
   "desc": "トレーナー資格を持つもとぶ糀工房さんによる整体体験。",
   "exhibitor": "motobu",
   "status": "仮",
   "meet": "開始5分前にブースへお越しください。来られない場合は、当日枠の方にお譲りします"
  },
  {
   "id": "ashimomi_10",
   "name": "足もみ体験 10:00の枠",
   "short": "10時",
   "zone": "C-1 ケアブース",
   "time": "10:00〜10:10",
   "duration": "10分",
   "target": "大人（体験したい小中学生・未就学児もOK）",
   "capacity": 1,
   "reserve": true,
   "unit": "名",
   "desc": "",
   "exhibitor": "kazetotaiyo",
   "status": "確定",
   "group": "ashimomi",
   "meet": "開始5分前にブースへお越しください。来られない場合は、当日枠の方にお譲りします",
   "start": "10:00",
   "end": "10:10"
  },
  {
   "id": "ashimomi_11",
   "name": "足もみ体験 11:00の枠",
   "short": "11時",
   "zone": "C-1 ケアブース",
   "time": "11:00〜11:10",
   "duration": "10分",
   "target": "大人（体験したい小中学生・未就学児もOK）",
   "capacity": 1,
   "reserve": true,
   "unit": "名",
   "desc": "",
   "exhibitor": "kazetotaiyo",
   "status": "確定",
   "group": "ashimomi",
   "meet": "開始5分前にブースへお越しください。来られない場合は、当日枠の方にお譲りします",
   "start": "11:00",
   "end": "11:10"
  },
  {
   "id": "ashimomi_12",
   "name": "足もみ体験 12:00の枠",
   "short": "12時",
   "zone": "C-1 ケアブース",
   "time": "12:00〜12:10",
   "duration": "10分",
   "target": "大人（体験したい小中学生・未就学児もOK）",
   "capacity": 1,
   "reserve": true,
   "unit": "名",
   "desc": "",
   "exhibitor": "kazetotaiyo",
   "status": "確定",
   "group": "ashimomi",
   "meet": "開始5分前にブースへお越しください。来られない場合は、当日枠の方にお譲りします",
   "start": "12:00",
   "end": "12:10"
  },
  {
   "id": "ashimomi_13",
   "name": "足もみ体験 13:00の枠",
   "short": "13時",
   "zone": "C-1 ケアブース",
   "time": "13:00〜13:10",
   "duration": "10分",
   "target": "大人（体験したい小中学生・未就学児もOK）",
   "capacity": 1,
   "reserve": true,
   "unit": "名",
   "desc": "",
   "exhibitor": "kazetotaiyo",
   "status": "確定",
   "group": "ashimomi",
   "meet": "開始5分前にブースへお越しください。来られない場合は、当日枠の方にお譲りします",
   "start": "13:00",
   "end": "13:10"
  },
  {
   "id": "ashimomi_14",
   "name": "足もみ体験 14:00の枠",
   "short": "14時",
   "zone": "C-1 ケアブース",
   "time": "14:00〜14:10",
   "duration": "10分",
   "target": "大人（体験したい小中学生・未就学児もOK）",
   "capacity": 1,
   "reserve": true,
   "unit": "名",
   "desc": "",
   "exhibitor": "kazetotaiyo",
   "status": "確定",
   "group": "ashimomi",
   "meet": "開始5分前にブースへお越しください。来られない場合は、当日枠の方にお譲りします",
   "start": "14:00",
   "end": "14:10"
  },
  {
   "id": "kids_am",
   "name": "運動あそび 午前の部（子ども・親子）",
   "short": "午前の部",
   "zone": "B 動くゾーン",
   "time": "午前（時間は調整中）",
   "duration": "30分（案）",
   "target": "子ども・親子",
   "capacity": 15,
   "reserve": true,
   "unit": "名",
   "desc": "",
   "exhibitor": "rena",
   "status": "仮",
   "group": "kids",
   "meet": "開始5分前にブースへお越しください。来られない場合は、当日枠の方にお譲りします"
  },
  {
   "id": "kids_pm",
   "name": "運動あそび 午後の部（小学校高学年・中学生）",
   "short": "午後の部",
   "zone": "B 動くゾーン",
   "time": "午後（時間は調整中）",
   "duration": "30分（案）",
   "target": "小学校高学年・中学生",
   "capacity": 15,
   "reserve": true,
   "unit": "名",
   "desc": "",
   "exhibitor": "rena",
   "status": "仮",
   "group": "kids",
   "meet": "開始5分前にブースへお越しください。来られない場合は、当日枠の方にお譲りします"
  }
 ],
 "exhibitors": {
  "hapisma": {
   "name": "ハピスマチーム",
   "people": "棚原 ななさん（保育士）・さおりさん（助産師）・ひとみさん（管理栄養士）",
   "tag": "保育士・助産師・管理栄養士の3人チーム",
   "intro": "産後のママと赤ちゃんに寄り添う3人チーム。困ったことがあったらいつでも頼れる場所づくりと、一緒に楽しめるイベントを月1回開催しています。「1人じゃないよ、頼りたいとき頼ってね」",
   "instagram": "https://www.instagram.com/happy.smile787/",
   "line": ""
  },
  "kazetotaiyo": {
   "name": "風と太陽",
   "people": "大城 ゆりえさん",
   "tag": "台湾式足もみ",
   "intro": "北中城村にある台湾式足もみ。足の反射区にアプローチする本格的な足もみです。",
   "instagram": "https://www.instagram.com/kaze.to.taiyo/",
   "line": ""
  },
  "yuimaru": {
   "name": "ゆいまーる",
   "people": "池原 あかねさん",
   "tag": "よもぎ蒸し・骨盤調整・水整体",
   "intro": "北中城小学校のすぐ近く。よもぎ蒸しや骨盤調整、水を使う新しい施術「水整体」が人気の完全予約制サロンです。",
   "instagram": "https://www.instagram.com/yuimarl_kitanaka/",
   "line": ""
  },
  "kubatore": {
   "name": "クバトレ",
   "people": "久場 創さん",
   "tag": "理学療法士・体芯力®認定指導者",
   "intro": "北中城村にある「頑張らないトレーニング・整体」。理学療法士として、スポーツをするお子さんから大人まで体をサポートしています。",
   "instagram": "",
   "line": "",
   "web": "https://kubatore.com/"
  },
  "motobu": {
   "name": "もとぶ糀工房 みら",
   "people": "嘉手苅 舞子さん・もときさん",
   "tag": "発酵食品・トレーナー資格",
   "intro": "本部町で、自家製の糀を使った甘酒やお味噌をつくる工房。ご夫婦ともトレーナー資格を持つ、健康と発酵のプロです。",
   "instagram": "https://www.instagram.com/motobukouji.85/",
   "line": "",
   "web": "https://motobukouji.stores.jp/"
  },
  "rena": {
   "name": "又吉 れなさん",
   "people": "又吉 れなさん",
   "tag": "アニマルフロー有資格トレーナー",
   "intro": "動きを引き出すプロ。子どもたちに大人気の、楽しく体を動かすトレーニングを届けています。",
   "instagram": "https://www.instagram.com/rena_trainer.oki/",
   "line": ""
  },
  "yuidocoro": {
   "name": "ゆいどころ",
   "people": "比嘉 なつき（作業療法士）",
   "tag": "企画運営・受付",
   "intro": "女性の為の整体 ゆいどころ。北中城村安谷屋のプライベートサロン。",
   "instagram": "https://www.instagram.com/yuidocoro_2021/",
   "line": "",
   "web": "https://www.yuidocoro.com/"
  }
 }
};
