// booths.js — booths.json をそのまま埋め込んだもの（file:// でも動くように fetch を使いません）
// 事実の正は booths.json です。内容を変えるときは booths.json を直してから、このファイルを作り直してください。
window.FESTA_DATA = {
 "event": {
  "name": "北中城村ウェルネススポーツフェスタ2026",
  "date": "2026-12-13",
  "dateLabel": "2026年12月13日（日）",
  "time": "10:00〜15:00",
  "venue": "北中城村中央公民館 ホール",
  "address": "沖縄県中頭郡北中城村字仲順435",
  "parking": "無料駐車場139台",
  "organizer": "主催：北中城村（企画振興課）／運営：北中城村観光協会／運営受託：ゆいどころ",
  "fee": "入場・体験 無料",
  "contact": "ゆいどころ（比嘉）080-6484-5121"
 },
 "booths": [
  {
   "id": "haihai",
   "name": "ハイハイレース",
   "short": "はいはい",
   "zone": "B 動くゾーン（舞台）",
   "time": "10:50〜11:20",
   "duration": "1レース5分・3レース",
   "target": "ずりばい、または、ハイハイができる赤ちゃんと保護者（月齢の制限なし）",
   "capacity": 12,
   "capacityNote": "9/12 なつきさん指示：午前の部12人",
   "reserve": true,
   "unit": "組",
   "desc": "ずりばいでゴールしてもよし！ ずりばい＆ハイハイで進んでもよし！ もちろん、素早いハイハイでゴールしてもよし！ どんな進み方でも大丈夫🙆‍♀️✨ 今しかできないかわいいレースにしちゃいましょー🥰💕",
   "exhibitor": "hapisma",
   "status": "確定",
   "meet": "開始10分前に舞台の前へ集合してください。時間までに来られない場合は、当日枠の方にお譲りします",
   "start": "10:50",
   "end": "11:20",
   "ages": [
    "baby"
   ]
  },
  {
   "id": "yochiyochi",
   "name": "よちよちレース",
   "short": "よちよち",
   "zone": "B 動くゾーン（舞台）",
   "time": "13:35〜14:05",
   "duration": "1レース5分・3レース",
   "target": "よちよち歩き始めたお子さん、よちよちして、ハイハイするお子さんと保護者（月齢の制限なし）",
   "capacity": 12,
   "capacityNote": "9/12 なつきさん指示：午後の部12人",
   "reserve": true,
   "unit": "組",
   "desc": "歩き始めたばかりのお子さんや、よちよち歩きとハイハイの“ハイブリッド”なお子さんたちのレースです！ ケガのないよう、スタッフとボランティアがそっと見守ります。かわいい姿を、みんなで応援しましょう！",
   "exhibitor": "hapisma",
   "status": "確定",
   "meet": "開始10分前に舞台の前へ集合してください。時間までに来られない場合は、当日枠の方にお譲りします",
   "start": "13:35",
   "end": "14:05",
   "ages": [
    "baby",
    "toddler"
   ]
  },
  {
   "id": "kids",
   "name": "運動あそび（午前）／動きやすいカラダづくり（午後）",
   "short": "運動あそび",
   "zone": "B 動くゾーン",
   "time": "午前の部／午後の部（時間は調整中）",
   "duration": "30分",
   "target": "午前＝〜小学生・親子／午後＝小学生〜中・高生・保護者",
   "capacity": 30,
   "reserve": true,
   "unit": "名",
   "desc": "午前の部は、あそび要素を取り入れながらカラダを動かしていきます！ 午後の部は、様々な動きで、どのスポーツにも活かせる動きづくり！ 各回の定員20名（予約15名）。水分補給は各自お持ちください。",
   "exhibitor": "rena",
   "status": "仮",
   "capacityNote": "9/16 RENAさん企画書：各回 定員20名・予約15名",
   "slots": [
    "kids_am",
    "kids_pm"
   ],
   "meet": "開始5分前にブースへお越しください。来られない場合は、当日枠の方にお譲りします",
   "ages": [
    "toddler",
    "kids",
    "teen"
   ]
  },
  {
   "id": "chair",
   "name": "チェアエクササイズ（年配の方向け）",
   "short": "チェア体操",
   "zone": "B 動くゾーン（舞台の前）",
   "time": "午前の最初（10:00〜・30分・案）",
   "duration": "30分（案）",
   "target": "年配の方・イスに座ったまま動きたい方（親子での見学も歓迎）",
   "capacity": 15,
   "reserve": true,
   "unit": "名",
   "desc": "イスに座ったままできる、やさしい体操の集団プログラム。定員30名のうち15名を事前予約でお受けします。残りは当日その場でどうぞ。",
   "exhibitor": "motobu",
   "status": "仮",
   "capacityNote": "9/16 なつきさん：定員30・事前予約15",
   "meet": "開始5分前にブースへお越しください。来られない場合は、当日枠の方にお譲りします",
   "ages": [
    "senior",
    "adult"
   ]
  },
  {
   "id": "adult",
   "name": "大人向けエクササイズ（クバトレ・午前）",
   "short": "大人エクササイズ",
   "zone": "B 動くゾーン（舞台の前）",
   "time": "午前（時間は調整中）",
   "duration": "30分（案）",
   "target": "大人（親子でのご参加も大歓迎）",
   "capacity": 15,
   "reserve": true,
   "unit": "名",
   "desc": "体芯軸（たいしんじく）を取り入れながら、運動不足を解消しよう。親子でのご参加も大歓迎です。",
   "exhibitor": "kubatore",
   "status": "仮",
   "capacityNote": "予約15（仮）",
   "meet": "開始5分前にお越しください。来られない場合は、当日枠の方にお譲りします",
   "ages": [
    "adult",
    "senior"
   ]
  },
  {
   "id": "kubatore_pm",
   "name": "大人とお子さまの対決あそび（クバトレ・午後）",
   "short": "対決あそび",
   "zone": "B 動くゾーン（舞台の前）",
   "time": "午後（時間は調整中）",
   "duration": "30分（案）",
   "target": "小学生〜大人（親子・家族で）",
   "capacity": 15,
   "capacityNote": "9/16 なつきさん：予約15人",
   "reserve": true,
   "unit": "名",
   "desc": "勝負しながら体を動かす！ 大人とお子さまの対決の運動あそびや、ケガ予防のための運動をご用意します。楽しみながらもトレーニングの要素を取り入れた、おもしろワーク。ぜひご体験ください。",
   "exhibitor": "kubatore",
   "status": "仮",
   "meet": "開始5分前にブースへお越しください。来られない場合は、当日枠の方にお譲りします",
   "ages": [
    "kids",
    "teen",
    "adult"
   ]
  },
  {
   "id": "ashimomi",
   "name": "足もみ体験",
   "short": "足もみ",
   "zone": "C-1 ケアブース",
   "time": "10時・11時・12時・13時・14時（各10分）",
   "duration": "10分",
   "target": "大人（体験したい小中学生・未就学児もOK）",
   "capacity": 5,
   "capacityNote": "9/12 なつきさん指示：5枠×1人",
   "reserve": true,
   "unit": "名",
   "desc": "「寝ても疲れがとれない」「なんとなく不調が続く」そんなことありませんか？足は全身を支える土台。台湾式の本格足もみで、足が軽くなり、全身が温まる感覚を体験してみませんか？",
   "exhibitor": "kazetotaiyo",
   "status": "確定",
   "caution": "妊娠初期（妊娠中で不安な方）、生理中、重度の心疾患のある方は受けられないことがあります",
   "slots": [
    "ashimomi_10",
    "ashimomi_11",
    "ashimomi_12",
    "ashimomi_13",
    "ashimomi_14"
   ],
   "meet": "開始5分前にブースへお越しください。来られない場合は、当日枠の方にお譲りします",
   "ages": [
    "toddler",
    "kids",
    "adult",
    "senior"
   ]
  },
  {
   "id": "seitai_yuimaru",
   "name": "リラクゼーション整体体験（ゆいまーる）",
   "short": "整体",
   "zone": "C-2 ケアブース",
   "time": "10時・11時・12時・13時・14時（各20分）",
   "duration": "20分",
   "target": "大人（小学生以上のお子さまも受けられます）",
   "capacity": 5,
   "capacityNote": "9/16 なつきさん：足もみと同じ 10・11・12・13・14時の5枠×1人（事前予約は5枠のみ）",
   "reserve": true,
   "unit": "名",
   "desc": "呼吸と天然水を取り入れた整体を20分体験（施術15分＋アフターカウンセリング5分）。頑張ることに慣れた心と身体に、自分をいたわる時間を。セラピスト歴20年以上の経験を生かし、自分を大切にする心地よさを感じられるはず。癒しをもっと日常に。",
   "exhibitor": "yuimaru",
   "status": "確定",
   "meet": "開始5分前にブースへお越しください。来られない場合は、当日枠の方にお譲りします",
   "ages": [
    "kids",
    "teen",
    "adult",
    "senior"
   ],
   "slots": [
    "seitai_yuimaru_10",
    "seitai_yuimaru_11",
    "seitai_yuimaru_12",
    "seitai_yuimaru_13",
    "seitai_yuimaru_14"
   ]
  },
  {
   "id": "seitai_yuimaru_10",
   "name": "リラクゼーション整体体験 10:00の枠",
   "short": "10時",
   "zone": "C-2 ケアブース",
   "time": "10:00〜10:20",
   "duration": "20分",
   "target": "大人（小学生以上のお子さまも受けられます）",
   "capacity": 1,
   "reserve": true,
   "unit": "名",
   "desc": "",
   "exhibitor": "yuimaru",
   "status": "確定",
   "group": "seitai_yuimaru",
   "meet": "開始5分前にブースへお越しください。来られない場合は、当日枠の方にお譲りします",
   "start": "10:00",
   "end": "10:20"
  },
  {
   "id": "seitai_yuimaru_11",
   "name": "リラクゼーション整体体験 11:00の枠",
   "short": "11時",
   "zone": "C-2 ケアブース",
   "time": "11:00〜11:20",
   "duration": "20分",
   "target": "大人（小学生以上のお子さまも受けられます）",
   "capacity": 1,
   "reserve": true,
   "unit": "名",
   "desc": "",
   "exhibitor": "yuimaru",
   "status": "確定",
   "group": "seitai_yuimaru",
   "meet": "開始5分前にブースへお越しください。来られない場合は、当日枠の方にお譲りします",
   "start": "11:00",
   "end": "11:20"
  },
  {
   "id": "seitai_yuimaru_12",
   "name": "リラクゼーション整体体験 12:00の枠",
   "short": "12時",
   "zone": "C-2 ケアブース",
   "time": "12:00〜12:20",
   "duration": "20分",
   "target": "大人（小学生以上のお子さまも受けられます）",
   "capacity": 1,
   "reserve": true,
   "unit": "名",
   "desc": "",
   "exhibitor": "yuimaru",
   "status": "確定",
   "group": "seitai_yuimaru",
   "meet": "開始5分前にブースへお越しください。来られない場合は、当日枠の方にお譲りします",
   "start": "12:00",
   "end": "12:20"
  },
  {
   "id": "seitai_yuimaru_13",
   "name": "リラクゼーション整体体験 13:00の枠",
   "short": "13時",
   "zone": "C-2 ケアブース",
   "time": "13:00〜13:20",
   "duration": "20分",
   "target": "大人（小学生以上のお子さまも受けられます）",
   "capacity": 1,
   "reserve": true,
   "unit": "名",
   "desc": "",
   "exhibitor": "yuimaru",
   "status": "確定",
   "group": "seitai_yuimaru",
   "meet": "開始5分前にブースへお越しください。来られない場合は、当日枠の方にお譲りします",
   "start": "13:00",
   "end": "13:20"
  },
  {
   "id": "seitai_yuimaru_14",
   "name": "リラクゼーション整体体験 14:00の枠",
   "short": "14時",
   "zone": "C-2 ケアブース",
   "time": "14:00〜14:20",
   "duration": "20分",
   "target": "大人（小学生以上のお子さまも受けられます）",
   "capacity": 1,
   "reserve": true,
   "unit": "名",
   "desc": "",
   "exhibitor": "yuimaru",
   "status": "確定",
   "group": "seitai_yuimaru",
   "meet": "開始5分前にブースへお越しください。来られない場合は、当日枠の方にお譲りします",
   "start": "14:00",
   "end": "14:20"
  },
  {
   "id": "conditioning",
   "name": "スポーツコンディショニング・整体ブース（クバトレ）",
   "short": "コンディショニング",
   "zone": "C-3 ケアブース",
   "time": "クバトレさんの集団プログラムがない時間（15分）",
   "duration": "15分",
   "target": "スポーツをするお子さま・大人（一般の大人のコンディショニングも）",
   "capacity": 3,
   "capacityNote": "9/16 なつきさん：事前予約3人",
   "reserve": true,
   "unit": "名",
   "desc": "スポーツ中のケガを防ぐ、あなたに合わせた体の使い方をお伝えします。自分の体の特性がわかると、体の不調を解決するきっかけになります。一度、ご自身の体の特徴を知る機会をつくってみませんか？",
   "exhibitor": "kubatore",
   "status": "仮",
   "meet": "開始5分前にブースへお越しください。来られない場合は、当日枠の方にお譲りします",
   "ages": [
    "kids",
    "teen",
    "adult"
   ]
  },
  {
   "id": "kidscond",
   "name": "キッズスポーツコンディショニング（もときさん）",
   "short": "キッズコンディショニング",
   "zone": "C-4 ケアブース",
   "time": "11時・12時・13時・14時（各15分）",
   "duration": "15分",
   "target": "スポーツや運動が大好きなお子さま",
   "capacity": 4,
   "capacityNote": "9/16 なつきさん：11・12・13・14時 各1人。ほかは当日その場で予約",
   "reserve": true,
   "unit": "名",
   "desc": "スポーツや運動大好きなお子さまたち集合！ 今よりももっと動ける体になるためのコンディショニングです。遊びにきてね。",
   "exhibitor": "motobu",
   "status": "仮",
   "slots": [
    "kidscond_11",
    "kidscond_12",
    "kidscond_13",
    "kidscond_14"
   ],
   "meet": "開始5分前にブースへお越しください。来られない場合は、当日枠の方にお譲りします",
   "ages": [
    "kids",
    "teen"
   ]
  },
  {
   "id": "stretch",
   "name": "ストレッチ＆コンディショニング（舞子さん）",
   "short": "ストレッチ",
   "zone": "C-5 ケアブース",
   "time": "10時・11時・13時・14時（各15分）。12時はお休み",
   "duration": "15分",
   "target": "お子さまから大人、年配の方まで",
   "capacity": 4,
   "capacityNote": "9/16 なつきさん：10時から受付可。12時は空けて4人（10・11・13・14時 各1人）",
   "reserve": true,
   "unit": "名",
   "desc": "リラクゼーションの要素も入れながら、ストレッチや体のコンディショニングを整えていきます。日ごろのお疲れさまな体を癒しに来てください。",
   "exhibitor": "motobu",
   "status": "仮",
   "slots": [
    "stretch_10",
    "stretch_11",
    "stretch_13",
    "stretch_14"
   ],
   "meet": "開始5分前にブースへお越しください。来られない場合は、当日枠の方にお譲りします",
   "ages": [
    "toddler",
    "kids",
    "teen",
    "adult",
    "senior"
   ]
  },
  {
   "id": "ashimomi_10",
   "name": "足もみ体験 10:00の枠",
   "short": "10時",
   "zone": "C-1 ケアブース",
   "time": "10:00〜10:10",
   "duration": "10分",
   "target": "大人（体験したい小中学生・未就学児もOK）",
   "capacity": 1,
   "reserve": true,
   "unit": "名",
   "desc": "",
   "exhibitor": "kazetotaiyo",
   "status": "確定",
   "group": "ashimomi",
   "meet": "開始5分前にブースへお越しください。来られない場合は、当日枠の方にお譲りします",
   "start": "10:00",
   "end": "10:10"
  },
  {
   "id": "ashimomi_11",
   "name": "足もみ体験 11:00の枠",
   "short": "11時",
   "zone": "C-1 ケアブース",
   "time": "11:00〜11:10",
   "duration": "10分",
   "target": "大人（体験したい小中学生・未就学児もOK）",
   "capacity": 1,
   "reserve": true,
   "unit": "名",
   "desc": "",
   "exhibitor": "kazetotaiyo",
   "status": "確定",
   "group": "ashimomi",
   "meet": "開始5分前にブースへお越しください。来られない場合は、当日枠の方にお譲りします",
   "start": "11:00",
   "end": "11:10"
  },
  {
   "id": "ashimomi_12",
   "name": "足もみ体験 12:00の枠",
   "short": "12時",
   "zone": "C-1 ケアブース",
   "time": "12:00〜12:10",
   "duration": "10分",
   "target": "大人（体験したい小中学生・未就学児もOK）",
   "capacity": 1,
   "reserve": true,
   "unit": "名",
   "desc": "",
   "exhibitor": "kazetotaiyo",
   "status": "確定",
   "group": "ashimomi",
   "meet": "開始5分前にブースへお越しください。来られない場合は、当日枠の方にお譲りします",
   "start": "12:00",
   "end": "12:10"
  },
  {
   "id": "ashimomi_13",
   "name": "足もみ体験 13:00の枠",
   "short": "13時",
   "zone": "C-1 ケアブース",
   "time": "13:00〜13:10",
   "duration": "10分",
   "target": "大人（体験したい小中学生・未就学児もOK）",
   "capacity": 1,
   "reserve": true,
   "unit": "名",
   "desc": "",
   "exhibitor": "kazetotaiyo",
   "status": "確定",
   "group": "ashimomi",
   "meet": "開始5分前にブースへお越しください。来られない場合は、当日枠の方にお譲りします",
   "start": "13:00",
   "end": "13:10"
  },
  {
   "id": "ashimomi_14",
   "name": "足もみ体験 14:00の枠",
   "short": "14時",
   "zone": "C-1 ケアブース",
   "time": "14:00〜14:10",
   "duration": "10分",
   "target": "大人（体験したい小中学生・未就学児もOK）",
   "capacity": 1,
   "reserve": true,
   "unit": "名",
   "desc": "",
   "exhibitor": "kazetotaiyo",
   "status": "確定",
   "group": "ashimomi",
   "meet": "開始5分前にブースへお越しください。来られない場合は、当日枠の方にお譲りします",
   "start": "14:00",
   "end": "14:10"
  },
  {
   "id": "kids_am",
   "name": "運動あそび 午前の部（〜小学生・親子）",
   "short": "午前の部",
   "zone": "B 動くゾーン",
   "time": "午前（時間は調整中）",
   "duration": "30分（案）",
   "target": "〜小学生・親子",
   "capacity": 15,
   "reserve": true,
   "unit": "名",
   "desc": "",
   "exhibitor": "rena",
   "status": "仮",
   "group": "kids",
   "meet": "開始5分前にブースへお越しください。来られない場合は、当日枠の方にお譲りします",
   "ages": [
    "toddler",
    "kids"
   ]
  },
  {
   "id": "kids_pm",
   "name": "動きやすいカラダづくり 午後の部（小学生〜中・高生・保護者）",
   "short": "午後の部",
   "zone": "B 動くゾーン",
   "time": "午後（時間は調整中）",
   "duration": "30分（案）",
   "target": "小学生〜中・高生・保護者",
   "capacity": 15,
   "reserve": true,
   "unit": "名",
   "desc": "",
   "exhibitor": "rena",
   "status": "仮",
   "group": "kids",
   "meet": "開始5分前にブースへお越しください。来られない場合は、当日枠の方にお譲りします",
   "ages": [
    "kids",
    "teen",
    "adult"
   ]
  },
  {
   "id": "kidscond_11",
   "name": "キッズスポーツコンディショニング 11:00の枠",
   "short": "11時",
   "zone": "C-4 ケアブース",
   "time": "11:00〜11:15",
   "duration": "15分",
   "target": "スポーツや運動が大好きなお子さま",
   "capacity": 1,
   "reserve": true,
   "unit": "名",
   "desc": "",
   "exhibitor": "motobu",
   "status": "仮",
   "group": "kidscond",
   "meet": "開始5分前にブースへお越しください。来られない場合は、当日枠の方にお譲りします",
   "start": "11:00",
   "end": "11:15"
  },
  {
   "id": "kidscond_12",
   "name": "キッズスポーツコンディショニング 12:00の枠",
   "short": "12時",
   "zone": "C-4 ケアブース",
   "time": "12:00〜12:15",
   "duration": "15分",
   "target": "スポーツや運動が大好きなお子さま",
   "capacity": 1,
   "reserve": true,
   "unit": "名",
   "desc": "",
   "exhibitor": "motobu",
   "status": "仮",
   "group": "kidscond",
   "meet": "開始5分前にブースへお越しください。来られない場合は、当日枠の方にお譲りします",
   "start": "12:00",
   "end": "12:15"
  },
  {
   "id": "kidscond_13",
   "name": "キッズスポーツコンディショニング 13:00の枠",
   "short": "13時",
   "zone": "C-4 ケアブース",
   "time": "13:00〜13:15",
   "duration": "15分",
   "target": "スポーツや運動が大好きなお子さま",
   "capacity": 1,
   "reserve": true,
   "unit": "名",
   "desc": "",
   "exhibitor": "motobu",
   "status": "仮",
   "group": "kidscond",
   "meet": "開始5分前にブースへお越しください。来られない場合は、当日枠の方にお譲りします",
   "start": "13:00",
   "end": "13:15"
  },
  {
   "id": "kidscond_14",
   "name": "キッズスポーツコンディショニング 14:00の枠",
   "short": "14時",
   "zone": "C-4 ケアブース",
   "time": "14:00〜14:15",
   "duration": "15分",
   "target": "スポーツや運動が大好きなお子さま",
   "capacity": 1,
   "reserve": true,
   "unit": "名",
   "desc": "",
   "exhibitor": "motobu",
   "status": "仮",
   "group": "kidscond",
   "meet": "開始5分前にブースへお越しください。来られない場合は、当日枠の方にお譲りします",
   "start": "14:00",
   "end": "14:15"
  },
  {
   "id": "stretch_10",
   "name": "ストレッチ＆コンディショニング 10:00の枠",
   "short": "10時",
   "zone": "C-5 ケアブース",
   "time": "10:00〜10:15",
   "duration": "15分",
   "target": "お子さまから大人、年配の方まで",
   "capacity": 1,
   "reserve": true,
   "unit": "名",
   "desc": "",
   "exhibitor": "motobu",
   "status": "仮",
   "group": "stretch",
   "meet": "開始5分前にブースへお越しください。来られない場合は、当日枠の方にお譲りします",
   "start": "10:00",
   "end": "10:15"
  },
  {
   "id": "stretch_11",
   "name": "ストレッチ＆コンディショニング 11:00の枠",
   "short": "11時",
   "zone": "C-5 ケアブース",
   "time": "11:00〜11:15",
   "duration": "15分",
   "target": "お子さまから大人、年配の方まで",
   "capacity": 1,
   "reserve": true,
   "unit": "名",
   "desc": "",
   "exhibitor": "motobu",
   "status": "仮",
   "group": "stretch",
   "meet": "開始5分前にブースへお越しください。来られない場合は、当日枠の方にお譲りします",
   "start": "11:00",
   "end": "11:15"
  },
  {
   "id": "stretch_13",
   "name": "ストレッチ＆コンディショニング 13:00の枠",
   "short": "13時",
   "zone": "C-5 ケアブース",
   "time": "13:00〜13:15",
   "duration": "15分",
   "target": "お子さまから大人、年配の方まで",
   "capacity": 1,
   "reserve": true,
   "unit": "名",
   "desc": "",
   "exhibitor": "motobu",
   "status": "仮",
   "group": "stretch",
   "meet": "開始5分前にブースへお越しください。来られない場合は、当日枠の方にお譲りします",
   "start": "13:00",
   "end": "13:15"
  },
  {
   "id": "stretch_14",
   "name": "ストレッチ＆コンディショニング 14:00の枠",
   "short": "14時",
   "zone": "C-5 ケアブース",
   "time": "14:00〜14:15",
   "duration": "15分",
   "target": "お子さまから大人、年配の方まで",
   "capacity": 1,
   "reserve": true,
   "unit": "名",
   "desc": "",
   "exhibitor": "motobu",
   "status": "仮",
   "group": "stretch",
   "meet": "開始5分前にブースへお越しください。来られない場合は、当日枠の方にお譲りします",
   "start": "14:00",
   "end": "14:15"
  }
 ],
 "exhibitors": {
  "hapisma": {
   "name": "チームハピスマ",
   "people": "なーなさん（保育士）・さおりさん（助産師）・ひーとさん（栄養士）",
   "tag": "保育士、助産師、栄養士の元気な3人チーム",
   "intro": "「1人じゃないよ。いつでも頼ってね。」保育士・栄養士・助産師の3人で活動している「ハピスマ」です。私たちは、産後のママと赤ちゃんが、安心して毎日を過ごせるように、そして親子で楽しく健康づくりに触れられる機会をつくりたいという想いから、月に1回、親子で楽しめるイベントを開催しています。",
   "instagram": "https://www.instagram.com/happy.smile787/",
   "line": ""
  },
  "kazetotaiyo": {
   "name": "風と太陽",
   "people": "大城 ゆりえさん（社会福祉士）",
   "tag": "台湾式足もみ",
   "photo": "img/kazetotaiyo.jpg",
   "intro": "北中城村にある台湾式足もみ。足の反射区にアプローチする本格的な足もみです。",
   "instagram": "https://www.instagram.com/kaze.to.taiyo/",
   "line": ""
  },
  "yuimaru": {
   "name": "ゆいまーる",
   "people": "池原 あかねさん",
   "tag": "よもぎ蒸し・骨盤調整・水整体",
   "intro": "北中城小学校のすぐ近く。よもぎ蒸しや骨盤調整、水を使う新しい施術「水整体」が人気の完全予約制サロンです。",
   "instagram": "https://www.instagram.com/yuimarl_kitanaka/",
   "line": ""
  },
  "kubatore": {
   "name": "クバトレ",
   "people": "久場 創さん",
   "tag": "理学療法士・体芯力®認定指導者",
   "intro": "北中城村にある「頑張らないトレーニング・整体」。理学療法士として、スポーツをするお子さんから大人まで体をサポートしています。",
   "instagram": "https://www.instagram.com/okinawa.seitai.kubatore/",
   "line": "",
   "web": "https://kubatore.com/"
  },
  "motobu": {
   "name": "もとぶ糀の里工房 みら／MK2",
   "people": "嘉手苅 舞子さん・もときさん",
   "photo": "img/motobukoji.jpg",
   "tag": "発酵食品（もとぶ糀の里工房 みら）・コンディショニング（MK2）",
   "intro": "本部町で、自家製の糀を使った甘酒やお味噌をつくる「もとぶ糀の里工房 みら」。コンディショニングは「MK2」の名前で活動しています。ご夫婦ともトレーナー資格を持つ、健康と発酵のプロです。",
   "instagram": "https://www.instagram.com/motobukouji.85/",
   "line": "",
   "web": "https://motobukouji.stores.jp/"
  },
  "rena": {
   "name": "RENA",
   "people": "RENA",
   "tag": "ムーブメント＆ライフパフォーマンスアップコーチ",
   "intro": "老若男女問わず、子ども〜大人まで楽しく軽やかに動けるカラダづくりのサポートをさせていただいております。",
   "instagram": "https://www.instagram.com/rena_trainer.oki/",
   "line": ""
  },
  "yuidocoro": {
   "name": "ゆいどころ",
   "people": "比嘉 なつき（作業療法士）",
   "tag": "企画運営・受付",
   "photo": "img/yuidocoro.jpg",
   "intro": "女性の為の整体 ゆいどころ。北中城村安谷屋のプライベートサロン。",
   "instagram": "https://www.instagram.com/yuidocoro_2021/",
   "line": "",
   "web": "https://www.yuidocoro.com/"
  }
 }
};
